### ISSUE TITLE
Incompatible with recent versions of rules_go

### ISSUE THREAD

**Issue by achew22** [pubref/rules_protobuf#156]
rules_protobuf and rules_go seem to be incompatible at this moment. I was going to send a PR to update you to the latest version looking like this:

```
$ git diff
diff --git a/WORKSPACE b/WORKSPACE
index 3490f97..3a33cdf 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -8,10 +8,10 @@ load("//protobuf:rules.bzl", "github_archive")
 
 github_archive(
     name = "io_bazel_rules_go",
-    commit = "ae70411645c171b2056d38a6a959e491949f9afe",  # v0.5.4
+    commit = "bcc7a4ff5a21ff2640f86cb302a7d976e33d89f1",
     org = "bazelbuild",
     repo = "rules_go",
-    sha256 = "ae91c1dfe9b943500f7486f2bb94b9887f881c7709474f3e170c95d414f79698",
+    sha256 = "98e3b73f63de52b60de9f25b8eab8cf8c3c77a71112a91effb9f1dc2926e161c",
 )
``` 

but I got 

```
Either remove the pre-existing rule from your WORKSPACE or exclude it from loading by rules_protobuf.
ERROR: Error evaluating WORKSPACE file
ERROR: /tmp/rules_protobuf/WORKSPACE:156:1: Traceback (most recent call last):
        File "/tmp/rules_protobuf/WORKSPACE", line 156
                ruby_proto_repositories()
        File "/tmp/rules_protobuf/ruby/rules.bzl", line 13, in ruby_proto_repositories
                cpp_proto_repositories()
        File "/tmp/rules_protobuf/cpp/rules.bzl", line 21, in cpp_proto_repositories
                proto_repositories(lang_deps = lang_deps, lang_requir..., ...)
        File "/tmp/rules_protobuf/protobuf/internal/proto_repositories.bzl", line 16, in proto_repositories
                require(keys = (protobuf_requires + lang...), <4 more arguments>)
        File "/tmp/rules_protobuf/protobuf/internal/require.bzl", line 73, in require
                _needs_install(key, data, verbose = verbose)
        File "/tmp/rules_protobuf/protobuf/internal/require.bzl", line 21, in _needs_install
                fail(msg)

An existing http_archive rule 'com_google_protobuf' was already loaded with a sha256 value of ''.  Refusing to overwrite this with the requested value ('542703acadc3f690d998f4641e1b988f15ba57ebca05fdfb1cd9095bec007948').
Either remove the pre-existing rule from your WORKSPACE or exclude it from loading by rules_protobuf.
```

I spent about hour or two looking into this and I can't figure it out. I think rules_go has started including some of the deps for doing protos but why is the shas256 empty?

I read the rules_go code and found out they check for the existance of a repo_rule and won't atempt to readd if it exists already. I tried reordering things so that I loaded the rules_go after the rules_proto go related repo_rules, but didn't seem to like that either.

```
$ git diff
diff --git a/WORKSPACE b/WORKSPACE
index 3490f97..58116c9 100644
--- a/WORKSPACE
+++ b/WORKSPACE
@@ -8,16 +8,12 @@ load("//protobuf:rules.bzl", "github_archive")
 
 github_archive(
     name = "io_bazel_rules_go",
-    commit = "ae70411645c171b2056d38a6a959e491949f9afe",  # v0.5.4
+    commit = "bcc7a4ff5a21ff2640f86cb302a7d976e33d89f1",
     org = "bazelbuild",
     repo = "rules_go",
-    sha256 = "ae91c1dfe9b943500f7486f2bb94b9887f881c7709474f3e170c95d414f79698",
+    sha256 = "98e3b73f63de52b60de9f25b8eab8cf8c3c77a71112a91effb9f1dc2926e161c",
 )
 
-load("@io_bazel_rules_go//go:def.bzl", "go_repositories")
-
-go_repositories()
-
 # ================================================================
 # closure js_proto_library support requires rules_closure
 # ================================================================
@@ -138,6 +134,10 @@ load("//grpc_gateway:rules.bzl", "grpc_gateway_proto_repositories")
 
 grpc_gateway_proto_repositories()
 
+load("@io_bazel_rules_go//go:def.bzl", "go_repositories")
+
+go_repositories()
+
 load("//node:rules.bzl", "node_proto_repositories")
 
 node_proto_repositories()
```

and now I get the output of

```
ERROR: /tmp/rules_protobuf/java/grpc-java-maven-deps/BUILD:2:1: no such package '@maven_grpc//': The repository could not be resolved and referenced by '//java/grpc-java-maven-deps:hello'
ERROR: Analysis of target '//java/grpc-java-maven-deps:hello' failed; build aborted: no such package '@maven_grpc//': The repository could not be resolved
```

Do you have any theories on how maven is affected by that change or why this version bump doesn't seem to be working so well?

**Comment by pcj** [comment]
Yes I ran into this as well and agree it's because rules_go and rules_protobuf are loading overlapping deps.  It is possible to omit / exclude deps when with rules_protobuf, but it's not so clean.

As for the reverse situation, I'll have to look into it, but I don't think I can do so before Friday.

**Comment by achew22** [comment]
@pcj, did you have any luck looking into this?

**Comment by pcj** [comment]
Haven't had a moment yet... (currently in SF for #bazelcon). But yeah the
first issue is due to rules_go and rules_protobuf trying to load same dep.
Not sure about the second, but it seems like there should be a way to break
the dependency on @maven_grpc for non-java rules...

**Comment by mattmoor** [comment]
FWIW, I'm hitting this too.  I'm trying to put together a `rules_k8s` sample of a Go `todocontroller`, but since K8s stuff requires such a recent version of `rules_go` this will (once I resolve other issues) block submitting that (it will break a separate `hellogrpc` sample).

**Comment by steeve** [comment]
This is according to rules_go README at https://github.com/bazelbuild/rules_go/blob/master/go/workspace.rst#id4:
> The list of dependencies it adds is quite long, there are a few listed below that you are more likely to want to know about and override, but it is by no means a complete list.
> com_google_protobuf : An http_archive for github.com/google/protobuf

**Comment by pcj** [comment]
Fixed by #159

**Comment by mattmoor** [comment]
Thanks!

**Comment by lucbettaieb** [comment]
I'm a bit of a newbie with all of this, but it looks as if I'm hitting this, too.  My `WORKSPACE` is:
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "cdaa8e35cf53ba539ebe5bf6a4a407f91a284594",
)
load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
  #commit = "..." # alternatively, use latest commit on master
)

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_repositories")
go_proto_repositories()
```

Any advice?

**Comment by promiseofcake** [comment]
@lucbettaieb what is your error? I think you might be missing a 
```
load("@org_pubref_rules_protobuf//protobuf:rules.bzl", "proto_repositories")
proto_repositories()
```

to get the underlying dependencies which should be declared before the language specific dependencies. 

You also might want to wait to init `rules_go` dependencies
```
go_rules_dependencies()
go_register_toolchains()
```

After pubref because they have their own declarations for protobuf dependencies: https://github.com/bazelbuild/rules_go/blob/master/go/private/repositories.bzl

Try
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "cdaa8e35cf53ba539ebe5bf6a4a407f91a284594",
)

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
  #commit = "..." # alternatively, use latest commit on master
)

load("@org_pubref_rules_protobuf//protobuf:rules.bzl", "proto_repositories")
proto_repositories()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_repositories")
go_proto_repositories()

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()
```

**Comment by lucbettaieb** [comment]
@promiseofcake Seems like I was missing the `proto_repositories` one!

Thanks for your help!  In the end, my `WORKSPACE` seems to work with the following:
```
git_repository(
    name = "io_bazel_rules_go",
    remote = "https://github.com/bazelbuild/rules_go.git",
    commit = "cdaa8e35cf53ba539ebe5bf6a4a407f91a284594",
)

git_repository(
  name = "org_pubref_rules_protobuf",
  remote = "https://github.com/pubref/rules_protobuf",
  tag = "v0.8.1",
  #commit = "..." # alternatively, use latest commit on master
)

load("@org_pubref_rules_protobuf//protobuf:rules.bzl", "proto_repositories")
proto_repositories()

load("@org_pubref_rules_protobuf//cpp:rules.bzl", "cpp_proto_repositories")
cpp_proto_repositories()

load("@org_pubref_rules_protobuf//go:rules.bzl", "go_proto_repositories")
go_proto_repositories()

load("@io_bazel_rules_go//go:def.bzl", "go_rules_dependencies", "go_register_toolchains")
go_rules_dependencies()
go_register_toolchains()
```
