### ISSUE TITLE
gogo_proto: can't build with bazel 0.8.0

### ISSUE THREAD

**Issue by jmuk** [pubref/rules_protobuf#164]
Our project uses gogo protos, and the latest release (bazel 0.8.0) can't deal with the current definition. It says like:

```
ERROR: /usr/local/google/home/mukai/gopath/src/istio.io/istio/security/proto/BUILD:5:1: Traceback (most recent call last):
        File "/usr/local/google/home/mukai/gopath/src/istio.io/istio/security/proto/BUILD", line 5
                gogoslick_proto_library(name = "go_default_library", impor..."}, <6 more arguments>)
        File "/usr/local/google/home/mukai/.cache/bazel/_bazel_mukai/1c0d5af62b066712c82d8b015c5a20e8/external/org_pubref_rules_protobuf/gogo/rules.bzl", line 123, in gogoslick_proto_library                                                                      
                gogo_proto_library(name, langs, go_prefix, protos, <17 more arguments>)                                           
        File "/usr/local/google/home/mukai/.cache/bazel/_bazel_mukai/1c0d5af62b066712c82d8b015c5a20e8/external/org_pubref_rules_protobuf/gogo/rules.bzl", line 153, in gogo_proto_library
                go_proto_deps += GRPC_COMPILE_DEPS     
trying to mutate a frozen object      
```

**Comment by pcj** [comment]
Thanks for reporting.  We need to get bazel 0.8.0 on the testing matrix.
