### ISSUE TITLE
nano_proto_repositories not working when included in WORKSPACE

### ISSUE THREAD

**Issue by paladine** [pubref/rules_protobuf#182]
I added this to the end of my WORKSPACE

```
git_repository(
    name = "org_pubref_rules_protobuf",
    remote = "https://github.com/pubref/rules_protobuf",
    tag = "v0.8.1",
)
load("@org_pubref_rules_protobuf//java:rules.bzl", "nano_proto_repositories")
nano_proto_repositories()
```

And I receive this error message
```
ERROR: /home/tcj/src/blaze_test/WORKSPACE:125:1: Traceback (most recent call last):
	File "/home/tcj/src/blaze_test/WORKSPACE", line 125
		nano_proto_repositories()
	File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/org_pubref_rules_protobuf/java/rules.bzl", line 58, in nano_proto_repositories
		proto_repositories(lang_requires = lang_requires, lan..., ...)
	File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/org_pubref_rules_protobuf/protobuf/internal/proto_repositories.bzl", line 16, in proto_repositories
		require(keys = (protobuf_requires + lang...), <4 more arguments>)
	File "/home/tcj/.cache/bazel/_bazel_tcj/86df34957ac88767728a08679bac58bf/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl", line 68, in require
		fail(("Unknown workspace dependency: ...))
Unknown workspace dependency: com_google_protobuf_nano_protobuf_javanano
ERROR: Error evaluating WORKSPACE file
```

**Comment by paladine** [comment]
It seems to be working when checking out with the latest commit
