### ISSUE TITLE
Unable to load package for 'org_pubref_rules_protobuf/java/rules.bzl'

### ISSUE THREAD

**Issue by ananthpnj** [pubref/rules_protobuf#255]
```bash
Navins-MacBook-Air:helloworld navinsethia$ bazel test examples/...
ERROR: /Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/internal/proto_compile.bzl:745:21: Traceback (most recent call last):
	File "/Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/internal/proto_compile.bzl", line 735
		rule(implementation = _proto_compile_..., <3 more arguments>)
	File "/Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/internal/proto_compile.bzl", line 744, in rule
		attr.label_list(allow_files = FileType([".proto"...))
	File "/Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/internal/proto_compile.bzl", line 745, in attr.label_list
		FileType([".proto"])
FileType function is not available. You may use a list of strings instead. You can temporarily reenable the function by passing the flag --incompatible_disallow_filetype=false
ERROR: error loading package '': in /Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/rules.bzl: Extension file 'protobuf/internal/proto_compile.bzl' has errors
ERROR: error loading package '': in /Users/navinsethia/Documents/Projects/rules_protobuf/protobuf/rules.bzl: Extension file 'protobuf/internal/proto_compile.bzl' has errors
INFO: Elapsed time: 0.077s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)
````

**Comment by pcj** [comment]
Hello @ananthpnj this repo is about to be archived, the newer version is https://github.com/stackb/rules_proto/
