### ISSUE TITLE
Why do we need compile protoc each time?

### ISSUE THREAD

**Issue by zhexuany** [pubref/rules_protobuf#97]
To me, it is tedious to do so. Obviously, the reason we chose to use bazel is because of the speed. If we compile protoc each time. It is dead slow!!!

**Comment by prestonvanloon** [comment]
Hi @zhexuany, can you give a detailed example? How are you using it to require protoc to run on each build? Bazel should be caching the incremental builds.

**Comment by zhexuany** [comment]
@prestonvanloon 

My `BUILD` looks like this.
```
package(default_visibility = ["//visibility:public"])

filegroup(
    name = "protos",
    srcs = glob([
         "*.proto",
         "gogoproto/*.proto",
    ]),
)

load("@org_pubref_rules_protobuf//java:rules.bzl", "java_proto_library")

java_proto_library(
    name = "java",
    protos = [":protos"],
    imports = [
            'external/com_github_google_protobuf/src',
            'src/main/proto',
              
    ],
    verbose = 0, # 0=no output, 1=show protoc command, 2+ more...
    inputs = ["@com_github_google_protobuf//:well_known_protos"],
)
```

Yes, bazel do cache last build that is partial reason why bazel being so fast. My point is we can let user specify  the path of `protoc` instead of compiling it from source from scratch.

**Comment by prestonvanloon** [comment]
You could probably override that dependency in your WORKSPACE like:
```python
java_proto_repositories(
  overrides = {
    "protoc": {
      "actual": "//tools:protoc",
      # was "actual": "@com_github_google_protobuf//:protoc",
    }
  },
)
```

where there is a BUILD in your tools directory that exports your system protoc
```python
genrule(
  name = "protoc",
  srcs = [],
  outs = ["protoc"],
  cmd = "cp $(which protoc) $@",
)
```
But that kind of defeats the purpose of incremental builds...

Unless you are running `bazel clean --expunge`, you should only have to build protoc one time.

**Comment by zhexuany** [comment]
@prestonvanloon 

I tried your way. But I got following error:

```
ERROR: /home/zhexuany/repo/java/tikv-client-java/WORKSPACE:123:1: Traceback (most recent call last):
	File "/home/zhexuany/repo/java/tikv-client-java/WORKSPACE", line 123
		java_proto_repositories(overrides = {"protoc": {"actual"..."}})
	File "/home/zhexuany/.cache/bazel/_bazel_zhexuany/f5238cb0016009912a6011daf5fa6cc1/external/org_pubref_rules_protobuf/java/rules.bzl", line 46, in java_proto_repositories
		proto_repositories(lang_deps = lang_deps, lang_requir..., ...)
	File "/home/zhexuany/.cache/bazel/_bazel_zhexuany/f5238cb0016009912a6011daf5fa6cc1/external/org_pubref_rules_protobuf/protobuf/internal/proto_repositories.bzl", line 14, in proto_repositories
		require(keys = protobuf_requires + lang_..., <4 more arguments>)
	File "/home/zhexuany/.cache/bazel/_bazel_zhexuany/f5238cb0016009912a6011daf5fa6cc1/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl", line 77, in require
		_install(required, verbose)
	File "/home/zhexuany/.cache/bazel/_bazel_zhexuany/f5238cb0016009912a6011daf5fa6cc1/external/org_pubref_rules_protobuf/protobuf/internal/require.bzl", line 46, in _install
		rule(**d)
missing mandatory named-only argument 'name' while calling bind(*, name, actual = ?).
ERROR: Error evaluating WORKSPACE file.
ERROR: package contains errors: src/main/java/com/pingcap/tikv.
ERROR: error loading package 'external': Package 'external' contains errors.
```

**Comment by prestonvanloon** [comment]
Yeah, I'm not sure if it'll work. It was more of a hack anyway.

**Comment by pcj** [comment]
Hi @zhexuany are you having to clean your repo often for some other reason? Like @prestonvanloon mentioned, protoc compilation should be a rare event.

**Comment by pcj** [comment]
Closing due to inactivity.
